title: "Brian's Blog"
author: "Brian Stremel"
description: "Blog personal"
url: "https://brianstremel.github.io"
baseurl: "/blog"

markdown: kramdown
highlighter: rouge

permalink: /:title/

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
